import { describe, it, expect } from 'vitest';
import { GET } from './route';

/**
 * Tests app/llms.txt/route.ts itself — just the HTTP wiring (status,
 * content-type). The actual content is generated by lib/llmsTxt.ts's
 * `buildLlmsTxt`, covered separately in lib/llmsTxt.test.ts, since a
 * Next.js route file may only export route handlers.
 */
describe('GET /llms.txt', () => {
  it('serves plain text with a 200', async () => {
    const res = await GET();
    expect(res.status).toBe(200);
    expect(res.headers.get('Content-Type')).toBe('text/plain; charset=utf-8');
  });

  it('body matches buildLlmsTxt()', async () => {
    const { buildLlmsTxt } = await import('@/lib/llmsTxt');
    const body = await (await GET()).text();
    expect(body).toBe(buildLlmsTxt());
  });
});
